apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-inference-model-secret
type: Opaque
stringData:
  INFERENCE_MODEL: llama-4-scout-17b-16e-w4a16
  VLLM_URL: https://llama-4-scout-17b-16e-w4a16-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com:443/v1
  VLLM_TLS_VERIFY: 'false'
  VLLM_API_TOKEN: temporary-token