apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - serviceAccount.yaml

configMapGenerator:
    - name: run-config
      files:
        - run.yaml
