apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: chatbot-ui
spec:
  to:
    kind: Service
    name: chatbot-ui
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
