kind: Service
apiVersion: v1
metadata:
  name: ocp-agent-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 7860
      targetPort: 7860
  type: ClusterIP
  selector:
    app: ocp-agent-service
